on: [push]

name: VM deployment in azure

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

        - name: Login to Azure
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Checkout source code
          uses: actions/checkout@v2

        - name: Deploy ARM template
          uses: azure/cli@v2
          with:
            inlineScript: |
              az deployment group create \
              --name VMDeployment \
              --resource-group AzureDeploy \
              --template-file armtemplate/ubuntu.json \
              --parameters adminUsername=azureuser \
              --parameters adminPasswordOrKey=${{ secrets.ADMINPASSWORD}}
